package personalproject;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import static java.lang.String.valueOf;
import static java.lang.System.exit;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Manage_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Manage_GUI
     */
    ListBanhMi lbm = new ListBanhMi();
    DefaultTableModel model;
    int voteThit = 0, voteCha = 0;

    public Manage_GUI() {
        initComponents();
        myInit();
        setDefaultLable();
        setDefaultVote();
        readFile();
    }

    private void myInit() {
        model = (DefaultTableModel) tbBanhMi.getModel();
        tbBanhMi.setModel(model);
    }

    private void readFile() {
        lbm.readFile("input.txt");
        for (BanhMi bm : lbm.al) {
            add1RowInTable(bm);
        }
    }

    private void setDefaultLable() {
        lbTmp.setText("Drink");
    }

    private void setDefaultVote() {
        lbVote.setText("0");
    }

    private void add1RowInTable(BanhMi bm) {
        if (bm instanceof BanhMiThit) {
            model.addRow(new Object[]{
                bm.getId(), bm.getBreadFilling(), bm.getSize(), ((BanhMiThit) bm).getDrink(), "", bm.getPrice()
            });
        } else {
            BanhMiCha bmc = (BanhMiCha) bm;
            model.addRow(new Object[]{
                bmc.getId(), bmc.getBreadFilling(), bmc.getSize(), "", bmc.getCoupons(), bmc.getPrice()
            });
        }
    }

    private void deleteTable() {
        model.setRowCount(0);
    }

    private boolean checkId(String id) {
        for (int i = 0; i < model.getRowCount(); i++) {
            if (id.equals(model.getValueAt(i, 0))) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBreadFilling = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        lbTmp = new javax.swing.JLabel();
        txtTmp = new javax.swing.JTextField();
        cbBanhMi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbVote = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBanhMi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btAddNew = new javax.swing.JButton();
        btSortByPrice = new javax.swing.JButton();
        btDeleteAll = new javax.swing.JButton();
        btPrintList = new javax.swing.JButton();
        btDeleteById = new javax.swing.JButton();
        btPrintListByType = new javax.swing.JButton();
        btPrintListByVote = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btTotalMoney = new javax.swing.JButton();
        btVote = new javax.swing.JButton();
        btFindById = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btDeleteByClick = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        pnInfo.setBackground(new java.awt.Color(102, 102, 102));
        pnInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 153)), "Information Sheet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Script", 0, 14), new java.awt.Color(255, 51, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bread Filling");

        jLabel5.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Size");

        lbTmp.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        lbTmp.setForeground(new java.awt.Color(255, 255, 255));

        cbBanhMi.setBackground(new java.awt.Color(153, 153, 153));
        cbBanhMi.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        cbBanhMi.setForeground(new java.awt.Color(255, 255, 255));
        cbBanhMi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banh Mi Thit", "Banh Mi Cha" }));
        cbBanhMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBanhMiActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vote: ");

        lbVote.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnInfoLayout = new javax.swing.GroupLayout(pnInfo);
        pnInfo.setLayout(pnInfoLayout);
        pnInfoLayout.setHorizontalGroup(
            pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInfoLayout.createSequentialGroup()
                        .addComponent(cbBanhMi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnInfoLayout.createSequentialGroup()
                        .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTmp, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtSize)
                            .addComponent(txtBreadFilling)
                            .addComponent(txtId)))))
            .addGroup(pnInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbVote, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(63, 63, 63))
        );
        pnInfoLayout.setVerticalGroup(
            pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbBanhMi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBreadFilling, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lbVote, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tbBanhMi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Bread Filling", "Size", "Drink", "Coupons", "Prices"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBanhMi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBanhMiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBanhMi);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)), "Funtion Sheet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 14), new java.awt.Color(255, 51, 0))); // NOI18N

        btAddNew.setBackground(new java.awt.Color(255, 153, 204));
        btAddNew.setText("Add New");
        btAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddNewActionPerformed(evt);
            }
        });

        btSortByPrice.setBackground(new java.awt.Color(153, 255, 153));
        btSortByPrice.setText("Sort By Price");
        btSortByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortByPriceActionPerformed(evt);
            }
        });

        btDeleteAll.setBackground(new java.awt.Color(255, 153, 153));
        btDeleteAll.setText("Delete All");
        btDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteAllActionPerformed(evt);
            }
        });

        btPrintList.setBackground(new java.awt.Color(0, 153, 153));
        btPrintList.setText("Print List");
        btPrintList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintListActionPerformed(evt);
            }
        });

        btDeleteById.setBackground(new java.awt.Color(255, 153, 153));
        btDeleteById.setText("Delete By Id");
        btDeleteById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteByIdActionPerformed(evt);
            }
        });

        btPrintListByType.setBackground(new java.awt.Color(0, 153, 153));
        btPrintListByType.setText("Print List By Type");
        btPrintListByType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintListByTypeActionPerformed(evt);
            }
        });

        btPrintListByVote.setBackground(new java.awt.Color(0, 153, 153));
        btPrintListByVote.setText("Print List By Vote");
        btPrintListByVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintListByVoteActionPerformed(evt);
            }
        });

        btUpdate.setBackground(new java.awt.Color(255, 204, 204));
        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btTotalMoney.setBackground(new java.awt.Color(204, 204, 255));
        btTotalMoney.setText("Total Money");
        btTotalMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalMoneyActionPerformed(evt);
            }
        });

        btVote.setBackground(new java.awt.Color(204, 204, 255));
        btVote.setForeground(new java.awt.Color(0, 153, 153));
        btVote.setText("Vote");
        btVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoteActionPerformed(evt);
            }
        });

        btFindById.setBackground(new java.awt.Color(255, 204, 153));
        btFindById.setText("Find By Id");
        btFindById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindByIdActionPerformed(evt);
            }
        });

        btExit.setBackground(new java.awt.Color(255, 0, 0));
        btExit.setForeground(new java.awt.Color(255, 255, 102));
        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btDeleteByClick.setBackground(new java.awt.Color(255, 153, 153));
        btDeleteByClick.setText("Delete By Click");
        btDeleteByClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteByClickActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(0, 255, 204));
        jButton1.setText("Write File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSortByPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btTotalMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPrintList, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btDeleteById)
                            .addComponent(btFindById, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btVote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDeleteByClick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btPrintListByType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPrintListByVote))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDeleteByClick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDeleteById, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btPrintList, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPrintListByType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSortByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btFindById, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btVote, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btPrintListByVote, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setText("jLabel2");

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("BANH MI MANAGE PROGRAM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printListByType(int i) {
        if (i == 0) {
            for (BanhMi bm : lbm.listByType(0)) {
                add1RowInTable(bm);
            }
        } else {
            for (BanhMi bm : lbm.listByType(1)) {
                add1RowInTable(bm);
            }
        }
    }

    private void cbBanhMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBanhMiActionPerformed
        // TODO add your handling code here:
        if (cbBanhMi.getSelectedIndex() == 0) {
            lbTmp.setText("Drink");
            lbVote.setText(valueOf(voteThit));
        } else {
            lbTmp.setText("Coupons");
            lbVote.setText(valueOf(voteCha));
        }
    }//GEN-LAST:event_cbBanhMiActionPerformed

    private boolean deleteById(String id) {
        if (lbm.deleteById(id)) {
            JOptionPane.showMessageDialog(null, "Delete Successful!");
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Delete Fail, Not Found This Id!");
            int i = JOptionPane.showConfirmDialog(null, "Do you want to re-write?", "Notice", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.NO_OPTION == i) {
                return true;
            }
        }
        return false;
    }

    private void btVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoteActionPerformed
        // TODO add your handling code here:
        if (cbBanhMi.getSelectedIndex() == 0) {
            voteThit++;
        } else {
            voteCha++;
        }
        if (cbBanhMi.getSelectedIndex() == 0) {
            lbVote.setText(valueOf(voteThit));
        } else {
            lbVote.setText(valueOf(voteCha));
        }

    }//GEN-LAST:event_btVoteActionPerformed

    private void btPrintListByTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintListByTypeActionPerformed
        // TODO add your handling code here:
        String choice = JOptionPane.showInputDialog("Which type do you want to choose? Thit/Cha");
        deleteTable();
        if (choice.equalsIgnoreCase("Thit")) {
            printListByType(0);
        } else {
            printListByType(1);
        }
    }//GEN-LAST:event_btPrintListByTypeActionPerformed

    private void btPrintListByVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintListByVoteActionPerformed
        // TODO add your handling code here:
        String choice = JOptionPane.showInputDialog("Do you want to print a list with more or less votes ?more/less");
        deleteTable();
        if (voteThit > voteCha) {
            if (choice.equalsIgnoreCase("more")) {
                printListByType(0);
            } else {
                printListByType(1);
            }
        } else if (voteThit < voteCha) {
            if (choice.equalsIgnoreCase("more")) {
                printListByType(1);
            } else {
                printListByType(0);
            }
        } else if (voteThit == voteCha) {
            JOptionPane.showMessageDialog(null, "The Number Of Vote 'Thit' equal 'Cha' ");
        }
    }//GEN-LAST:event_btPrintListByVoteActionPerformed

    private void btAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddNewActionPerformed
        // TODO add your handling code here:
        if (checkId(txtId.getText())) {
            if (cbBanhMi.getSelectedIndex() == 0) {
                BanhMiThit bmt = new BanhMiThit(txtTmp.getText(), txtId.getText(), txtBreadFilling.getText(), Integer.parseInt(txtSize.getText()));
                lbm.addInList(bmt);
                add1RowInTable(bmt);
            } else {
                BanhMiCha bmc = new BanhMiCha(Integer.parseInt(txtTmp.getText()), txtId.getText(), txtBreadFilling.getText(), Integer.parseInt(txtSize.getText()));
                lbm.addInList(bmc);
                add1RowInTable(bmc);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Id Illegal");
        }
    }//GEN-LAST:event_btAddNewActionPerformed

    private void btPrintListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintListActionPerformed
        // TODO add your handling code here:
        deleteTable();
        for (BanhMi bm : lbm.al) {
            add1RowInTable(bm);
        }
    }//GEN-LAST:event_btPrintListActionPerformed

    private void btDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteAllActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog("Please, Enter 'Confirm' to delete all DataBase and Table");
        if (s.equalsIgnoreCase("Confirm")) {
            lbm.al.clear();
            deleteTable();
        }
    }//GEN-LAST:event_btDeleteAllActionPerformed

    private void btDeleteByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteByIdActionPerformed
        // TODO add your handling code here:
        while (true) {
            String id = JOptionPane.showInputDialog("Enter Id you want to delete");
            if (deleteById(id)) {
                break;
            }
        }
        btPrintListActionPerformed(evt);
    }//GEN-LAST:event_btDeleteByIdActionPerformed

    private void btDeleteByClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteByClickActionPerformed
        // TODO add your handling code here:
        int i = tbBanhMi.getSelectedRow();
        if (i > -1) {
            String id = model.getValueAt(i, 0).toString();
            deleteById(id);
        }
        btPrintListActionPerformed(evt);
    }//GEN-LAST:event_btDeleteByClickActionPerformed

    private void btSortByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortByPriceActionPerformed
        // TODO add your handling code here:
        lbm.sortByPrice();
        btPrintListActionPerformed(evt);
    }//GEN-LAST:event_btSortByPriceActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Notice", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == i) {
            exit(0);
        }
    }//GEN-LAST:event_btExitActionPerformed

    private void btTotalMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalMoneyActionPerformed
        // TODO add your handling code here:
        long sumThit = 0, sumCha = 0;
        for (BanhMi bm : lbm.al) {
            if (bm instanceof BanhMiThit) {
                sumThit += bm.getPrice();
            } else {
                sumCha += bm.getPrice();
            }
        }
        String type = JOptionPane.showInputDialog("Enter Type you want to sum(thit/cha/both):");
        if (type.equalsIgnoreCase("Thit")) {
            JOptionPane.showMessageDialog(null, sumThit + " VND");
        } else if (type.equalsIgnoreCase("Cha")) {
            JOptionPane.showMessageDialog(null, sumCha + "VND");
        } else {
            JOptionPane.showMessageDialog(null, (sumCha + sumThit) + " VND");
        }
    }//GEN-LAST:event_btTotalMoneyActionPerformed

    private void btFindByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindByIdActionPerformed
        // TODO add your handling code here:
        while (true) {
            String id = JOptionPane.showInputDialog("Enter Id:");
            if (lbm.findById(id) != null) {
                deleteTable();
                add1RowInTable(lbm.findById(id));
                break;
            } else {
                JOptionPane.showMessageDialog(null, "Not Found This Id");
                int i = JOptionPane.showConfirmDialog(null, "Do You Want to Re-Enter?", "Notice", JOptionPane.YES_NO_OPTION);
                if (JOptionPane.NO_OPTION == i) {
                    break;
                }
            }
        }
    }//GEN-LAST:event_btFindByIdActionPerformed

    private void tbBanhMiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBanhMiMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int i = tbBanhMi.getSelectedRow();
            txtId.setText(model.getValueAt(i, 0).toString());
            txtBreadFilling.setText(model.getValueAt(i, 1).toString());
            txtSize.setText(model.getValueAt(i, 2).toString());
            if (model.getValueAt(i, 4) == "") {
                txtTmp.setText(model.getValueAt(i, 3).toString());
                cbBanhMi.setSelectedIndex(0);
            } else {
                txtTmp.setText(model.getValueAt(i, 4).toString());
                cbBanhMi.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_tbBanhMiMouseClicked

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        int i = tbBanhMi.getSelectedRow();
        lbm.deleteById(model.getValueAt(i, 0).toString());
        deleteTable();
        btAddNewActionPerformed(evt);
    }//GEN-LAST:event_btUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fileName = JOptionPane.showInputDialog("Enter File Name:");
        lbm.writeFile(fileName);
        Path path = Paths.get(fileName);
        File file = new File("D:\\Learn Back-End\\Java_OOP\\Personal_Project\\PersonalProJect\\" + path);
        Desktop desktop = Desktop.getDesktop();
        if (file.exists()) {
            try {
                desktop.open(file);

            } catch (IOException ex) {
                System.out.println("IO Exception when open in Desktop!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddNew;
    private javax.swing.JButton btDeleteAll;
    private javax.swing.JButton btDeleteByClick;
    private javax.swing.JButton btDeleteById;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btFindById;
    private javax.swing.JButton btPrintList;
    private javax.swing.JButton btPrintListByType;
    private javax.swing.JButton btPrintListByVote;
    private javax.swing.JButton btSortByPrice;
    private javax.swing.JButton btTotalMoney;
    private javax.swing.JButton btUpdate;
    private javax.swing.JButton btVote;
    private javax.swing.JComboBox<String> cbBanhMi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTmp;
    private javax.swing.JLabel lbVote;
    private javax.swing.JPanel pnInfo;
    private javax.swing.JTable tbBanhMi;
    private javax.swing.JTextField txtBreadFilling;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtTmp;
    // End of variables declaration//GEN-END:variables
}
